### PR TITLE
Include errors from stderr for broken build output

### LINKED ISSUE #39: Unspecific error messages if the code does not compile
In the editor bug reports a lot of people wrote they saw `'/usr/local/go/bin/go test --json .' returned exit code 2: exit status 2` as error message which wasn't helpful for them. Is there something that could be improved?

I also see the generic "an error occurred" for certain solutions.

I will post some examples below.  
My feeling is this happens when the (test) code does not compile.

### LINKED ISSUE #40: No proper error message for old version of Lasagna
The lasagna exercise was changed to use a constant instead of a function for OvenTime.

Then I run the the old code (shown below) against the new tests, the general "an error occured" message shows up instead of an error message.

image

```go
package lasagna

// OvenTime returns the expected baking time in minutes.
func OvenTime() int {
    return 40
}

// RemainingOvenTime returns the remaining minutes based on the `actual` minutes already in the oven.
func RemainingOvenTime(actual int) int {
	return OvenTime() - actual
}

// PreparationTime calculates the time needed to prepare the lasagna based on the amount of layers.
func PreparationTime(numberOfLayers int) int {
	return numberOfLayers *2
}

// ElapsedTime calculates the total time needed to create and bake a lasagna.
func ElapsedTime(numberOfLayers, actualMinutesInOven int) int {
	return PreparationTime(numberOfLayers) + actualMinutesInOven
}
```

### PR DESCRIPTION
**Pull request by junedev**
Fixes #39 
Fixes #40

I manually checked all the cases mentioned in those tickets. All showed proper error messages now.

### CODE REVIEW

**Review by jmrunkle — APPROVED** [review]
These changes look good to me. Any reason not to go forward with this PR?

**Comment by junedev** [comment]
@jmrunkle There is a second part to fix some other cases. I changed the PR description so the issue stays open. This can be merged, not sure who can do that though.

**Comment by jmrunkle** [comment]
> not sure who can do that though.

I think @ErikSchierboom or @iHiD can approve and merge it.

**Comment by junedev** [comment]
@jmrunkle Sorry, changed my mind and put this back to draft. While working on the other cases I found a better way of solving this more generally. Will push the update soon.

**Comment by junedev** [comment]
Done. All cases from the issues should be covered now.

**Review by jmrunkle — APPROVED** [review]
Nice!

**Comment by jmrunkle** [comment]
Just verified that [maintainers-admin](https://github.com/orgs/exercism/teams/maintainers-admin) is precisely @iHiD and @ErikSchierboom - is it correct that these should always require approval by those two?

**Review by ekingery — APPROVED** [review]
Excellent - nice fix and thanks @junedev for taking good care of the tests and adding the new case!

**Comment by iHiD** [comment]
>  is it correct that these should always require approval by those two?

For test-runner stuff, yes, it needs signoff by one of us, as the consequences of it going wrong are very large for the site (e.g. a whole track stops working, or some malicious code gets merge that turns our servers into bitcoin farms, etc). Also, I like to be awake and online when tooling things are merged in case they have some negative effort during deploy (e.g. one the other day took down all our tooling servers because it caused them to run out of HDD space as there wasn't room on the machines for the extra images).

That said, for PRs written and reviewed by people we trust (e.g. everyone here) that don't change the Dockerfile, I normally just merge it without reading, which is what I'm about to do here :)

**Pull request merged**
