### PR TITLE
change output of test-runner on compile error to adhere to the standard

### LINKED ISSUE #11: No compilation errors are shown
I ran the following code:

```go
package go1a

// Describe takes an amount and returns a description.
func Describe(amount int) string {
	return ""
}

func Units(amount int) (int, int, int, int) {
	grosses := amount / 144
	amount %= 144
	
	scores := amount / 20
	amount %= 20
	
	dozens := amount / 12
	amount %= 12
	
	return (grosses, scores, dozens, amount)
}
```

This has a syntax error, but it didn't show up in the test output. Looking at the test results JSON, it has captured the compile error, but in the test itself and not in the top-level `message` property (see the [spec](https://github.com/exercism/automated-tests/blob/master/docs/interface.md#message)):

```json
{
	"status": "error",
	"tests": [
		{
			"name": "build",
			"status": "error",
			"expected": "",
			"actual": "",
			"message": "./go_1_a.go:18:17: syntax error: unexpected comma, expecting )"
		}
	]
}
```

For this reason., the compilation error message is not shown as the output. The test runner should output the compilation error in the top-level `message` property.

### PR DESCRIPTION
**Pull request by tehsphinx**
Fixes #11

### CODE REVIEW

**Comment by tehsphinx** [comment]
@ErikSchierboom: This change removes the extra test I created on a compile error to hold the error message and adds the error message on top level. The only output is then `status` and `message`. `tests` is null. Or should I omit that?

**Comment by ErikSchierboom** [comment]
@tehsphinx Awesome! Could you make the `tests` an empty array perhaps?

**Comment by tehsphinx** [comment]
```
{
	"status": "error",
	"message": "./sample_test.go:37:1: missing return at end of function",
	"tests": []
}
```

**Comment by ErikSchierboom** [comment]
Thanks!

**Pull request merged**
