### PR TITLE
Update to Go 1.20

### PR DESCRIPTION
**Pull request by andrerfcsantos**
## Description

This is part of the upgrade of the track to Go 1.20:

- Updated CI to run Go 1.20
- Updated golangci-lint
- Updated main `go.mod` file
  - This caused the linter to fail due to `ioutil` being deprecated.
  - Deprecations were also addressed.
- Updated Docker image
- Updated external dependencies
  - Updated [golang.org/x/text/language](https://pkg.go.dev/golang.org/x/text/language) to `0.7.0` to address [GO-2022-1059](https://pkg.go.dev/vuln/GO-2022-1059)
  - Regenerated the `go.sum` for external dependencies using a `go.mod` set to 1.18

## Related

PR that also should be merged for the track to be considered "upgraded":

- [ ] Update main repo: https://github.com/exercism/go/pull/2609

The following PRs should be merged eventually, but there's no rush since Go currently doesn't have the representer or the analyzer enabled:

- [ ] Update representer: https://github.com/exercism/go-representer/pull/34
- [ ] Update analyzer: https://github.com/exercism/go-analyzer/pull/40

### CODE REVIEW

**Comment by andrerfcsantos** [comment]
It seems the tests are now failing for 2 main reasons:

- `TestRunTests_broken`, which tests `testrunner/testdata/practice/broken/` seems to fail with an error of `returned exit code 1: exit status 1`, but the tests expect `returned exit code 2: exit status 2`.
- For `TestRunTests_passing` the field `message` in the json is slightly off. For the subtests, in the `message` field, the command is returning `[...]\n\n--- PASS: TestTrivialPass1/subtest_1.1[...]`, but the tests expect `[...]\n\n    --- PASS: TestTrivialPass1/subtest_1.1[...]`, i.e, the spaces before `--- PASS` are not present in the result of the command.

@junedev Do you know if this is due to the new format of `go test -json` and we can safely change what the tests expect  or is it a problem in the code that we must address? Can't find any details on the `go test -json` change other than the [release notes](https://tip.golang.org/doc/go1.20) which doesn't explain in detail what changed.

**Comment by junedev** [comment]
@andrerfcsantos I updated the expected json files to what I think they should be. Currently, some tests fail though because e.g. the text that is returned as result of a panic is not included anymore. We will need to fix the actual code for this. (Potentially something related to stdout vs stderr.)

**Review by junedev — COMMENTED** [review]
I think I fixed the issue. The problem was that in Go 1.18 the panic was reported as belonging to the subtest. In Go 1.20 it was marked with the name of the parent test. Because we remove parent tests, the message got lost. I added code to check whether the parent has a relevant message and moving it to the subtest.

**Review by junedev — APPROVED** [review]

**Comment by junedev** [comment]
@andrerfcsantos I undrafted this so Erik can have a look. The main repo can be updated whenever we want after this is merged, they are not on the same Go version anyway since we use "latest" here and an older version for the exercises.

The representer and analayzer are not live so also no dependency regarding the update there.

**Comment by andrerfcsantos** [comment]
@junedev This is great, thanks!

> The main repo can be updated whenever we want after this is merged, they are not on the same Go version anyway since we use "latest" here and an older version for the exercises. The representer and analayzer are not live so also no dependency regarding the update there.

Changed the descriptions accordingly.

> Would be good if you can double check the changes to the expected outputs look ok to you.

It does. As far as I understand, after the changes you made it's just a couple of spaces removed before the `---`, which I think is better.

**Review by ErikSchierboom — APPROVED** [review]

**Pull request merged**
