### PR TITLE
Fix for build failures during import phase

### PR DESCRIPTION
**Pull request by moshegood**
This is for issue: https://github.com/exercism/go-test-runner/issues/35

### CODE REVIEW

**Review by ekingery — APPROVED** [review]
Thank you for fixing this! Also for adding the test - nice. 

Unfortunately I can't take the time to set up my stack and verify the functionality, but the code looks good to me. 

And for future reference, I wouldn't be surprised if this breaks again, if the Golang team decides to prioritize this "cleanup": https://github.com/golang/go/issues/25989

**Comment by iHiD** [comment]
Thank you both!

**Comment by iHiD** [comment]
Deployed. Works brilliantly. Thank you 💙

**Comment by ErikSchierboom** [comment]
Thanks!

**Pull request merged**
